### PR TITLE
Fixed Aria hidden on the footer-link secondary text.

### PR DESCRIPTION
**Pull request by m6jones**
Used the same method you used for cards.

### CODE REVIEW

**Comment by dbatiste** [comment]
If I understand correctly, the `aria-hidden` that was being applied to the secondary text was not being honored when the AT was announcing the anchor...?

**Comment by m6jones** [comment]
That is correct. I am guessing the `aria-hidden` would have to be on the anchor.

**Comment by dbatiste** [comment]
This seems more complicated that I thought it should be.  The z-index stuff isn't ideal, and we'd need to make sure that dropdown menus still float on top of it.  Also, the resulting sibling selector that's needed to color the icon when the anchor is focused seems like an unnecessary complexity.   

Is it possible to only move the secondary text outside of the anchor and shift it left by 100% of it's width so that it would be positioned in top right corner still.  Or, it is possible to use `::after` pseudo-class to create the secondary text?

**Comment by m6jones** [comment]
So I experimented with the `::after` it won't work as it is still read by some screen readers. [https://www.smashingmagazine.com/2016/05/an-ultimate-guide-to-css-pseudo-classes-and-pseudo-elements/] So that is a no go. Also, it be messy setting the `content`

The other option is just bringing the `secondary-text` this works and is very simple to do however, it blocks the anchor. To fix it, I add more `z-index` to the `icon` and the `d2l-card-footer-link-secondary-text`

What are your thoughts?

**Comment by m6jones** [comment]
Yes, I agree with that. Otherwise it is annoying to edit later. I'll fix that.

**Pull request merged**
